version: '2.29'

services:
  spring-client:
    build: 
      context: ./spring-client
      dockerfile: ./src/main/docker/Dockerfile
    image: docker.io/fax4ever/spring-client:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      infinispan:
        condition: service_healthy
  infinispan:
    image: infinispan/server:15.0.5.Final
    hostname: my-infinispan
    ports:
      - "11222:11222"
    environment:
      - USER=xxxxxx
      - PASS=yyyyyy
    healthcheck:
      test: curl --fail http://my-infinispan:11222/rest/v2/container/health/status || exit 1
      interval: 1s
      timeout: 10s
      retries: 5