services:
  spring-client:
    build: 
      context: ./spring-client
      dockerfile: ./src/main/docker/Dockerfile
    image: docker.io/fax4ever/spring-client:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
  infinispan:
    image: infinispan/server:15.0.5.Final
    hostname: my-infinispan
    ports:
      - "11222:11222"
    environment:
      - USER=xxxxxx
      - PASS=yyyyyy